language: python
dist: xenial

env:
  global:
    PIP_PREFER_BINARY=true

python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"

before_install:
  - python -m pip install --upgrade pip
install:
  - pip install -r requirements.txt

# command to run tests
script:
   pytest

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - liufengrui18z@ict.ac.cn
  on_success: never # default: change
  on_failure: always # default: always


branches:
  only:
    - dev
    - master