# Project information
site_name: StreamAD
site_description: Anomaly detection for data streams in Python
site_author: liufr
site_url: https://github.io.fengrui_liu.StreamAD.com

# Repository
repo_name: Fengrui-Liu/StreamAD
repo_url: https://github.com/Fengrui-Liu/StreamAD



# Configuration
theme:
    name: material
    custom_dir: docs/overrides
    language: en
    palette:
        primary: indigo
        accent: indigo
    font:
        text: Roboto
        code: Roboto Mono
    # logo: img/river_square.svg
    # favicon: img/favicon.ico
    features:
        - navigation.tabs
        - navigation.instant


# Extras
extra:
    social:
      - icon: fontawesome/brands/github-alt
        link: https://github.com/Fengrui-Liu/StreamAD

# Google Analytics
# google_analytics:
#   - UA-63302552-3
#   - auto

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
        guess_lang: false
  - footnotes
  - toc:
        permalink: true
        toc_depth: "1-3"
  - pymdownx.details
  - pymdownx.arithmatex

plugins:
  - search
  - awesome-pages

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML

  - js/version-select.js
extra_css:
  - stylesheets/extra.css
  - css/version-select.css


  # Copyright
copyright: Copyright &copy; 2019 - 2020