version: 2.1

orbs:
  python: circleci/python@1.5.0
  codecov: codecov/codecov@3.2.2

jobs:
  build-main:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          command: pip install pytest coverage && coverage run -m pytest && coverage report coverage html
          name: Test-main
      - codecov/upload
    parallelism: 4


  build-dev:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          command: pip install pytest coverage && coverage run -m pytest && coverage report coverage html
          name: Test-dev
      - codecov/upload
    parallelism: 4

workflows:
  build-dev:
    jobs:
      - build-dev:
          filters:
            branches:
              only:
                - dev
  build-main:
    jobs:
      - build-main:
          filters:
            branches:
              only:
                - main