version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-main:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          command: pip install pytest && python -m pytest
          name: Test-main

  build-dev:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          command: pip install pytest && python -m pytest
          name: Test-dev


workflows:
  build-dev:
    jobs:
      - build-dev:
          filters:
            branches:
              only:
                - dev
  build-main:
    jobs:
      - build-main:
          filters:
            branches:
              only:
                - main