version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-main:
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          command: python -m pytest
          name: Test-main

  build-dev:
    steps:
      - checkout
      - run:
          command: python -m pytest
          name: Test-dev


workflows:
  build_dev:
    jobs:
      - build-dev:
          filters:
            branches:
              only:
                - dev
  build_main:
    jobs:
      - build-main:
          filters:
            branches:
              only:
                - main