{% set data = load_setup_py_data() %}

package:
  name: albumentations
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    run:
      {% for req in data.get('install_requires', []) %}
        - {{ req }}
      {% endfor %}

  run:
    run:
      {% for req in data.get('install_requires', []) %}
        - {{ req }}
      {% endfor %}


about:
  home: {{ data['url'] }}
  license_file:
    - LICENSE
summary: {{ data['description'] }}